#!/bin/bash
# Test Transaction Validation - Debug Script

echo "=========================================="
echo "Transaction Validation Debug Script"
echo "=========================================="
echo ""
echo "This script will help you test a transaction and see the debug logs."
echo ""
echo "Instructions:"
echo "1. Start your Docker containers: docker-compose up -d"
echo "2. Try to create a transaction in the tenant interface"
echo "3. Check the PHP error logs to see what's happening"
echo ""
echo "To view PHP error logs, run one of these commands:"
echo ""
echo "Option 1 - View Docker container logs:"
echo "  docker-compose logs -f --tail=100 php"
echo ""
echo "Option 2 - View PHP error log file (if logging to file):"
echo "  docker exec accounting-php cat /var/log/php_errors.log"
echo ""
echo "Option 3 - View Apache/Nginx error log:"
echo "  docker exec accounting-php cat /var/log/apache2/error.log"
echo "  # OR"
echo "  docker exec accounting-nginx cat /var/log/nginx/error.log"
echo ""
echo "=========================================="
echo "What to look for in the logs:"
echo "=========================================="
echo ""
echo "1. === VALIDATING TRANSACTION LINES ==="
echo "   - Shows each account being processed"
echo "   - Current balance, change, new balance"
echo ""
echo "2. === BALANCE CHANGES BY TYPE ==="
echo "   - Shows the total change for each account type"
echo ""
echo "3. === CURRENT EQUATION STATE ==="
echo "   - Shows the current balances of all account types"
echo ""
echo "4. === PROJECTED BALANCES ==="
echo "   - Shows what the balances would be after the transaction"
echo ""
echo "5. === EQUATION CHECK ==="
echo "   - Shows if the equation would remain balanced"
echo "   - If 'Is Balanced: NO', the transaction is blocked"
echo ""
echo "=========================================="
echo "Common Issues:"
echo "=========================================="
echo ""
echo "Issue 1: System accounts not tracked"
echo "  - Look for 'Is System Account: YES'"
echo "  - Should still show 'Change: X' being added to balance_changes_by_type"
echo ""
echo "Issue 2: Wrong normal balance"
echo "  - Check 'Normal Balance' for each account"
echo "  - Assets & Expenses should be 'debit'"
echo "  - Liabilities, Equity, Revenue should be 'credit'"
echo ""
echo "Issue 3: Wrong balance calculation"
echo "  - Check the 'Change' value"
echo "  - Debit to debit normal = positive change"
echo "  - Credit to credit normal = positive change"
echo "  - Opposite sides = negative change"
echo ""
echo "Issue 4: Equation doesn't balance"
echo "  - Check the 'Difference' value"
echo "  - Should be close to 0 (less than 0.01)"
echo "  - If large difference, one of the calculations is wrong"
echo ""
echo "=========================================="

